/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author alexis
 */
public class tableroPersonal extends javax.swing.JFrame {

    /**
     * Creates new form tableroPersonal
     */
    public tableroPersonal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CustomGameCreateScreen = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        LengthSlider = new javax.swing.JSlider();
        HeightSlider = new javax.swing.JSlider();
        LengthLabel = new javax.swing.JLabel();
        HeightLabel = new javax.swing.JLabel();
        CreateCustomBoard = new javax.swing.JButton();
        CustomGamePanel = new javax.swing.JPanel();
        SnakeOrLadder = new javax.swing.JComboBox();
        RollDice2 = new javax.swing.JButton();
        CustomDiceLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ingresoTxt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CustomGameCreateScreen.setBackground(new java.awt.Color(255, 153, 255));
        CustomGameCreateScreen.setPreferredSize(new java.awt.Dimension(1000, 700));

        jLabel8.setText("Board Length");

        jLabel9.setText("Board Height");

        LengthSlider.setMajorTickSpacing(1);
        LengthSlider.setMaximum(12);
        LengthSlider.setMinimum(5);
        LengthSlider.setMinorTickSpacing(1);
        LengthSlider.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                LengthSliderMouseClicked(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                LengthSliderMouseClicked1(evt);
            }
        });
        LengthSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LengthSliderMouseClicked2(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LengthSliderMouseClicked3(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LengthSliderMouseClicked4(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LengthSliderMouseClicked5(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LengthSliderMouseClicked6(evt);
            }
        });

        HeightSlider.setMaximum(12);
        HeightSlider.setMinimum(5);
        HeightSlider.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeightSliderMouseClicked(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                HeightSliderMouseClicked1(evt);
            }
        });
        HeightSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HeightSliderMouseClicked2(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HeightSliderMouseClicked3(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HeightSliderMouseClicked4(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeightSliderMouseClicked5(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                HeightSliderMouseClicked6(evt);
            }
        });

        LengthLabel.setText("12");

        HeightLabel.setText("12");

        CreateCustomBoard.setText("Create Board");
        CreateCustomBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateCustomBoardActionPerformed(evt);
            }
        });

        CustomGamePanel.setBackground(new java.awt.Color(255, 255, 255));
        CustomGamePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CustomGamePanelMouseReleased(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CustomGamePanelMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CustomGamePanelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout CustomGamePanelLayout = new javax.swing.GroupLayout(CustomGamePanel);
        CustomGamePanel.setLayout(CustomGamePanelLayout);
        CustomGamePanelLayout.setHorizontalGroup(
            CustomGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 772, Short.MAX_VALUE)
        );
        CustomGamePanelLayout.setVerticalGroup(
            CustomGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        SnakeOrLadder.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Snake", "Ladder" }));

        RollDice2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RollDice2ActionPerformed(evt);
            }
        });

        CustomDiceLabel.setBackground(new java.awt.Color(255, 255, 255));
        CustomDiceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("<html>\nInstructions:<<br>\nPress and drag the mouse from one box<br>\nto another to spawn snake or ladder</html>");

        jButton1.setText("Regreso");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ingresoTxt.setText("Ingreso TXT");
        ingresoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CustomGameCreateScreenLayout = new javax.swing.GroupLayout(CustomGameCreateScreen);
        CustomGameCreateScreen.setLayout(CustomGameCreateScreenLayout);
        CustomGameCreateScreenLayout.setHorizontalGroup(
            CustomGameCreateScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CustomGameCreateScreenLayout.createSequentialGroup()
                .addGroup(CustomGameCreateScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CustomGameCreateScreenLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(CustomGameCreateScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(CustomGameCreateScreenLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(HeightSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CustomGameCreateScreenLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(99, 99, 99)
                                .addComponent(LengthSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(46, 46, 46)
                        .addGroup(CustomGameCreateScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CustomGameCreateScreenLayout.createSequentialGroup()
                                .addGroup(CustomGameCreateScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LengthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(CustomGameCreateScreenLayout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(CustomDiceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 326, Short.MAX_VALUE))
                            .addGroup(CustomGameCreateScreenLayout.createSequentialGroup()
                                .addComponent(HeightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ingresoTxt)
                                .addGap(29, 29, 29))))
                    .addGroup(CustomGameCreateScreenLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(CustomGamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)))
                .addGroup(CustomGameCreateScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CreateCustomBoard)
                    .addComponent(SnakeOrLadder, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CustomGameCreateScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(CustomGameCreateScreenLayout.createSequentialGroup()
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(49, 49, 49))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CustomGameCreateScreenLayout.createSequentialGroup()
                            .addGap(7, 7, 7)
                            .addComponent(RollDice2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(70, 70, 70))
        );
        CustomGameCreateScreenLayout.setVerticalGroup(
            CustomGameCreateScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomGameCreateScreenLayout.createSequentialGroup()
                .addGroup(CustomGameCreateScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CustomGameCreateScreenLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(SnakeOrLadder, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(RollDice2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142)
                        .addComponent(jButton1))
                    .addGroup(CustomGameCreateScreenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(CustomGameCreateScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel8)
                            .addComponent(LengthSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LengthLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(CustomGameCreateScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(HeightSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CustomGameCreateScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(HeightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CreateCustomBoard)
                                .addComponent(ingresoTxt)))
                        .addGap(15, 15, 15)
                        .addComponent(CustomGamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(623, 623, 623)
                .addComponent(CustomDiceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CustomGameCreateScreen, javax.swing.GroupLayout.DEFAULT_SIZE, 1155, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CustomGameCreateScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LengthSliderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LengthSliderMouseClicked
        // TODO add your handling code here:
        LengthLabel.setText(String.valueOf(LengthSlider.getValue()));
    }//GEN-LAST:event_LengthSliderMouseClicked

    private void LengthSliderMouseClicked1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LengthSliderMouseClicked1
        // TODO add your handling code here:
        LengthLabel.setText(String.valueOf(LengthSlider.getValue()));
    }//GEN-LAST:event_LengthSliderMouseClicked1

    private void LengthSliderMouseClicked2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LengthSliderMouseClicked2
        // TODO add your handling code here:
        LengthLabel.setText(String.valueOf(LengthSlider.getValue()));
    }//GEN-LAST:event_LengthSliderMouseClicked2

    private void LengthSliderMouseClicked3(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LengthSliderMouseClicked3
        // TODO add your handling code here:
        LengthLabel.setText(String.valueOf(LengthSlider.getValue()));
    }//GEN-LAST:event_LengthSliderMouseClicked3

    private void LengthSliderMouseClicked4(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LengthSliderMouseClicked4
        // TODO add your handling code here:
        LengthLabel.setText(String.valueOf(LengthSlider.getValue()));
    }//GEN-LAST:event_LengthSliderMouseClicked4

    private void LengthSliderMouseClicked5(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LengthSliderMouseClicked5
        // TODO add your handling code here:
        LengthLabel.setText(String.valueOf(LengthSlider.getValue()));
    }//GEN-LAST:event_LengthSliderMouseClicked5

    private void LengthSliderMouseClicked6(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LengthSliderMouseClicked6
        // TODO add your handling code here:
        LengthLabel.setText(String.valueOf(LengthSlider.getValue()));
    }//GEN-LAST:event_LengthSliderMouseClicked6

    private void HeightSliderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeightSliderMouseClicked
        // TODO add your handling code here:
        HeightLabel.setText(String.valueOf(HeightSlider.getValue()));
    }//GEN-LAST:event_HeightSliderMouseClicked

    private void HeightSliderMouseClicked1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeightSliderMouseClicked1
        // TODO add your handling code here:
        HeightLabel.setText(String.valueOf(HeightSlider.getValue()));
    }//GEN-LAST:event_HeightSliderMouseClicked1

    private void HeightSliderMouseClicked2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeightSliderMouseClicked2
        // TODO add your handling code here:
        HeightLabel.setText(String.valueOf(HeightSlider.getValue()));
    }//GEN-LAST:event_HeightSliderMouseClicked2

    private void HeightSliderMouseClicked3(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeightSliderMouseClicked3
        // TODO add your handling code here:
        HeightLabel.setText(String.valueOf(HeightSlider.getValue()));
    }//GEN-LAST:event_HeightSliderMouseClicked3

    private void HeightSliderMouseClicked4(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeightSliderMouseClicked4
        // TODO add your handling code here:
        HeightLabel.setText(String.valueOf(HeightSlider.getValue()));
    }//GEN-LAST:event_HeightSliderMouseClicked4

    private void HeightSliderMouseClicked5(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeightSliderMouseClicked5
        // TODO add your handling code here:
        HeightLabel.setText(String.valueOf(HeightSlider.getValue()));
    }//GEN-LAST:event_HeightSliderMouseClicked5

    private void HeightSliderMouseClicked6(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeightSliderMouseClicked6
        // TODO add your handling code here:
        HeightLabel.setText(String.valueOf(HeightSlider.getValue()));
    }//GEN-LAST:event_HeightSliderMouseClicked6

    private void CreateCustomBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateCustomBoardActionPerformed
        // TODO add your handling code here:
      
        /**
        IniializeIcons();
        Players = new Player[numOfPlayers];
        if (numOfPlayers == 1) {
            Players[0] = new Player(Player1NameField.getText(), Color.RED);
        } else if (numOfPlayers == 2) {
            Players[0] = new Player(Player1NameField.getText(), Color.RED);
            Players[1] = new Player(Player2NameField.getText(), Color.MAGENTA);
        } else if (numOfPlayers == 3) {
            Players[0] = new Player(Player1NameField.getText(), Color.RED);
            Players[1] = new Player(Player2NameField.getText(), Color.MAGENTA);
            Players[2] = new Player(Player3NameField.getText(), Color.BLUE);
        }
        Customboardlength = LengthSlider.getValue();
        Customboardheight = HeightSlider.getValue();
        gfx = (Graphics2D) CustomGamePanel.getGraphics();
        gfx.setColor(Color.white);
        int h = (int) CustomGamePanel.getSize().getHeight();
        int l = (int) CustomGamePanel.getSize().getWidth();
        gfx.fillRect(0, 0, l, h);
        Customboxsize = 45;
        Snakes = new Snake[Customboardlength * Customboardheight];
        Ladders = new Ladder[Customboardlength * Customboardheight];
        moves=0;
        DrawPlayers();
        * */
    }//GEN-LAST:event_CreateCustomBoardActionPerformed

    private void CustomGamePanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomGamePanelMouseReleased
        // TODO add your handling code here:
       /**
        end = CustomGamePanel.getMousePosition();
        int a = Findcell(start);
        int b = Findcell(end);
        if (SnakeOrLadder.getSelectedItem().toString() == "Snake") {
            MakeSnake(a, b);
        } else if (SnakeOrLadder.getSelectedItem().toString() == "Ladder") {
            MakeLadder(a, b);
        }
        * */
    }//GEN-LAST:event_CustomGamePanelMouseReleased

    private void CustomGamePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomGamePanelMouseEntered
        // TODO add your handling code here:
       // DrawPlayers();
    }//GEN-LAST:event_CustomGamePanelMouseEntered

    private void CustomGamePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomGamePanelMousePressed
        // TODO add your handling code here:
    //    start = CustomGamePanel.getMousePosition();
    }//GEN-LAST:event_CustomGamePanelMousePressed

    private void RollDice2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RollDice2ActionPerformed
        // TODO add your handling code here:
     //   GameControl();
      //  RollDice2.setText(Players[moves % numOfPlayers].getName() + " Play");
    }//GEN-LAST:event_RollDice2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        interfaz regreso = new interfaz();
        regreso.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ingresoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoTxtActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateCustomBoard;
    private javax.swing.JLabel CustomDiceLabel;
    private javax.swing.JPanel CustomGameCreateScreen;
    private javax.swing.JPanel CustomGamePanel;
    private javax.swing.JLabel HeightLabel;
    private javax.swing.JSlider HeightSlider;
    private javax.swing.JLabel LengthLabel;
    private javax.swing.JSlider LengthSlider;
    private javax.swing.JButton RollDice2;
    private javax.swing.JComboBox SnakeOrLadder;
    private javax.swing.JButton ingresoTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
